export const PRODUCTS_DATA = {
  "herramientas-de-agricultura": {
    name: "Herramientas de Agricultura",
    description: "Encuentra la mejor selección de herramientas agrícolas profesionales",
    products: [
      {
        id: 1,
        name: "Arado Profesional 500",
        category: "Herramientas de Agricultura",
        price: 1200,
        image: "/professional-agricultural-plow.jpg",
        images: ["/professional-agricultural-plow.jpg"],
        brand: "AgroTech",
        description: "Arado de alta resistencia para terrenos difíciles",
        features: ["Acero reforzado de alta calidad", "Diseño ergonómico", "Fácil de transportar"],
        specs: ["Acero reforzado", "Peso: 45kg", "Ancho: 1.5m"],
        availability: "En stock",
        faqs: [
          { question: "¿Cuál es el peso máximo que puede arar?", answer: "Hasta 2 toneladas por hora" },
          { question: "¿Requiere mantenimiento especial?", answer: "Mantenimiento básico cada 6 meses" },
        ],
        connectivity: ["Bluetooth"],
      },
      {
        id: 2,
        name: "Cultivador Eléctrico 300",
        category: "Herramientas de Agricultura",
        price: 850,
        image: "/electric-cultivator-agricultural-tool.jpg",
        images: ["/electric-cultivator-agricultural-tool.jpg"],
        brand: "ElectroFarm",
        description: "Cultivador eléctrico para pequeñas y medianas parcelas",
        features: ["Motor eléctrico silencioso", "Control de velocidad variable", "Batería de larga duración"],
        specs: ["Motor 2.5HP", "Peso: 28kg", "Ancho: 1.2m"],
        availability: "En stock",
        faqs: [
          { question: "¿Cuánto dura la batería?", answer: "Aproximadamente 4 horas de uso continuo" },
          { question: "¿Es fácil de usar?", answer: "Sí, tiene controles intuitivos" },
        ],
        connectivity: ["WiFi"],
      },
      {
        id: 3,
        name: "Rastrillo Mecánico 400",
        category: "Herramientas de Agricultura",
        price: 650,
        image: "/mechanical-rake-agricultural-equipment.jpg",
        images: ["/mechanical-rake-agricultural-equipment.jpg"],
        brand: "MechaTools",
        description: "Rastrillo mecánico de precisión",
        features: ["Acero inoxidable resistente", "Dientes ajustables", "Construcción robusta"],
        specs: ["Acero inoxidable", "Peso: 35kg", "Ancho: 1.8m"],
        availability: "En stock",
        faqs: [{ question: "¿Los dientes son reemplazables?", answer: "Sí, son fáciles de cambiar" }],
        connectivity: [],
      },
      {
        id: 4,
        name: "Azadón Profesional Plus",
        category: "Herramientas de Agricultura",
        price: 450,
        image: "/professional-hoe-agricultural-tool.jpg",
        images: ["/professional-hoe-agricultural-tool.jpg"],
        brand: "ProTools",
        description: "Azadón ergonómico para trabajo intensivo",
        features: ["Mango ergonómico", "Hoja afilada de precisión", "Ligero y resistente"],
        specs: ["Mango de madera", "Peso: 3.5kg", "Hoja: 25cm"],
        availability: "En stock",
        faqs: [{ question: "¿Es adecuado para todo tipo de suelo?", answer: "Sí, funciona en la mayoría de suelos" }],
        connectivity: [],
      },
      {
        id: 5,
        name: "Arado Eléctrico 600",
        category: "Herramientas de Agricultura",
        price: 1500,
        image: "/electric-plow-agricultural-equipment.jpg",
        images: ["/electric-plow-agricultural-equipment.jpg"],
        brand: "AgroTech",
        description: "Arado eléctrico de última generación",
        features: ["Motor 3HP de alta potencia", "Sistema de control automático", "Bajo consumo energético"],
        specs: ["Motor 3HP", "Peso: 52kg", "Ancho: 1.6m"],
        availability: "En stock",
        faqs: [{ question: "¿Cuál es el consumo de energía?", answer: "Aproximadamente 2.5 kW por hora" }],
        connectivity: ["Bluetooth", "WiFi"],
      },
      {
        id: 6,
        name: "Cultivador Manual 200",
        category: "Herramientas de Agricultura",
        price: 320,
        image: "/manual-cultivator-hand-tool.jpg",
        images: ["/manual-cultivator-hand-tool.jpg"],
        brand: "MechaTools",
        description: "Cultivador manual de precisión",
        features: ["Acero templado de calidad", "Diseño compacto", "Fácil de manejar"],
        specs: ["Acero templado", "Peso: 2.8kg", "Ancho: 0.8m"],
        availability: "En stock",
        faqs: [{ question: "¿Es adecuado para huertos pequeños?", answer: "Perfecto para huertos y jardines" }],
        connectivity: [],
      },
    ],
  },
  aspersores: {
    name: "Aspersores",
    description: "Sistemas de riego profesionales para agricultura",
    products: [
      {
        id: 7,
        name: "Aspersor Rotatorio 360",
        category: "Aspersores",
        price: 280,
        image: "/rotary-sprinkler-irrigation-system.jpg",
        images: ["/rotary-sprinkler-irrigation-system.jpg"],
        brand: "AquaFlow",
        description: "Aspersor rotatorio de cobertura completa",
        features: ["Cobertura 360 grados", "Presión regulable", "Material resistente"],
        specs: ["Rango: 15m", "Presión: 2-4 bar", "Material: Latón"],
        availability: "En stock",
        faqs: [{ question: "¿Cuál es el rango de cobertura?", answer: "Hasta 15 metros de radio" }],
        connectivity: [],
      },
      {
        id: 8,
        name: "Aspersor Inteligente WiFi",
        category: "Aspersores",
        price: 450,
        image: "/smart-wifi-sprinkler-system.jpg",
        images: ["/smart-wifi-sprinkler-system.jpg"],
        brand: "SmartWater",
        description: "Aspersor con control remoto vía WiFi",
        features: ["Control remoto WiFi", "Programación automática", "Sensor de humedad"],
        specs: ["Rango: 20m", "Presión: 2-5 bar", "Control app"],
        availability: "En stock",
        faqs: [{ question: "¿Necesita instalación profesional?", answer: "No, instalación simple" }],
        connectivity: ["WiFi"],
      },
      {
        id: 9,
        name: "Aspersor Oscilante Pro",
        category: "Aspersores",
        price: 320,
        image: "/oscillating-sprinkler-professional.jpg",
        images: ["/oscillating-sprinkler-professional.jpg"],
        brand: "AquaFlow",
        description: "Aspersor oscilante para áreas grandes",
        features: ["Oscilación automática", "Cobertura rectangular", "Ajuste de presión"],
        specs: ["Rango: 25m", "Presión: 2-4 bar", "Ancho: 2m"],
        availability: "En stock",
        faqs: [{ question: "¿Cubre áreas grandes?", answer: "Sí, hasta 25 metros de largo" }],
        connectivity: [],
      },
    ],
  },
  desbrozadoras: {
    name: "Desbrozadoras",
    description: "Desbrozadoras profesionales para mantenimiento de terrenos",
    products: [
      {
        id: 10,
        name: "Desbrozadora Gasolina 50cc",
        category: "Desbrozadoras",
        price: 580,
        image: "/gasoline-brush-cutter-50cc.jpg",
        images: ["/gasoline-brush-cutter-50cc.jpg"],
        brand: "PowerCut",
        description: "Desbrozadora de gasolina de alta potencia",
        features: ["Motor 50cc potente", "Bajo nivel de ruido", "Fácil arranque"],
        specs: ["Motor: 50cc", "Potencia: 2.5HP", "Peso: 8.5kg"],
        availability: "En stock",
        faqs: [{ question: "¿Cuánto combustible consume?", answer: "Aproximadamente 0.5L por hora" }],
        connectivity: [],
      },
      {
        id: 11,
        name: "Desbrozadora Eléctrica 1800W",
        category: "Desbrozadoras",
        price: 420,
        image: "/electric-brush-cutter-1800w.jpg",
        images: ["/electric-brush-cutter-1800w.jpg"],
        brand: "ElectroTools",
        description: "Desbrozadora eléctrica silenciosa",
        features: ["Muy silenciosa", "Bajo mantenimiento", "Ecológica"],
        specs: ["Potencia: 1800W", "Peso: 5.2kg", "Cable: 50m"],
        availability: "En stock",
        faqs: [{ question: "¿Es segura para usar?", answer: "Sí, con protecciones de seguridad" }],
        connectivity: [],
      },
      {
        id: 12,
        name: "Desbrozadora Batería 40V",
        category: "Desbrozadoras",
        price: 650,
        image: "/battery-powered-brush-cutter-40v.jpg",
        images: ["/battery-powered-brush-cutter-40v.jpg"],
        brand: "PowerCut",
        description: "Desbrozadora a batería recargable",
        features: ["Batería recargable 40V", "Autonomía prolongada", "Sin cables"],
        specs: ["Batería: 40V", "Autonomía: 45min", "Peso: 4.8kg"],
        availability: "En stock",
        faqs: [{ question: "¿Cuánto tarda en cargar?", answer: "Aproximadamente 1 hora" }],
        connectivity: ["Bluetooth"],
      },
    ],
  },
  sillas: {
    name: "Sillas",
    description: "Sillas ergonómicas y profesionales",
    products: [
      {
        id: 13,
        name: "Silla Ergonómica Pro",
        category: "Sillas",
        price: 380,
        image: "/ergonomic-professional-office-chair.jpg",
        images: ["/ergonomic-professional-office-chair.jpg"],
        brand: "ComfortSeating",
        description: "Silla ergonómica con soporte lumbar",
        features: ["Soporte lumbar ajustable", "Altura regulable", "Respaldo reclinable"],
        specs: ["Material: Malla", "Altura ajustable", "Peso máx: 150kg"],
        availability: "En stock",
        faqs: [{ question: "¿Es cómoda para largas jornadas?", answer: "Sí, diseñada para comodidad máxima" }],
        connectivity: [],
      },
      {
        id: 14,
        name: "Silla Ejecutiva Premium",
        category: "Sillas",
        price: 520,
        image: "/premium-executive-office-chair.jpg",
        images: ["/premium-executive-office-chair.jpg"],
        brand: "LuxurySeating",
        description: "Silla ejecutiva de cuero genuino",
        features: ["Cuero genuino premium", "Reclinable 180 grados", "Reposabrazos ajustables"],
        specs: ["Material: Cuero", "Reclinable", "Peso máx: 180kg"],
        availability: "En stock",
        faqs: [{ question: "¿El cuero es fácil de limpiar?", answer: "Sí, con un paño húmedo" }],
        connectivity: [],
      },
    ],
  },
  tuberias: {
    name: "Tuberías",
    description: "Tuberías de alta calidad para sistemas de riego",
    products: [
      {
        id: 15,
        name: 'Tubería PVC 1"',
        category: "Tuberias",
        price: 45,
        image: "/pvc-pipe-1-inch-irrigation.jpg",
        images: ["/pvc-pipe-1-inch-irrigation.jpg"],
        brand: "PipeFlow",
        description: "Tubería PVC de 1 pulgada por metro",
        features: ["PVC de alta calidad", "Resistente a la corrosión", "Fácil de instalar"],
        specs: ["Material: PVC", 'Diámetro: 1"', "Presión: 10 bar"],
        availability: "En stock",
        faqs: [{ question: "¿Cuál es la vida útil?", answer: "Más de 50 años" }],
        connectivity: [],
      },
      {
        id: 16,
        name: 'Tubería Polietileno 3/4"',
        category: "Tuberias",
        price: 35,
        image: "/plastic-pipe.jpg",
        images: ["/plastic-pipe.jpg"],
        brand: "PipeFlow",
        description: "Tubería de polietileno flexible",
        features: ["Polietileno flexible", "Resistente a temperaturas", "Fácil de enrollar"],
        specs: ["Material: PE", 'Diámetro: 3/4"', "Presión: 8 bar"],
        availability: "En stock",
        faqs: [{ question: "¿Es flexible?", answer: "Sí, muy flexible y fácil de manejar" }],
        connectivity: [],
      },
    ],
  },
  "madera-contrachapada": {
    name: "Madera Contrachapada",
    description: "Madera contrachapada de calidad premium",
    products: [
      {
        id: 17,
        name: "Contrachapado 18mm Premium",
        category: "Madera Contrachapada",
        price: 85,
        image: "/plywood-sheet.jpg",
        images: ["/plywood-sheet.jpg"],
        brand: "WoodPro",
        description: "Lámina de contrachapado de 18mm",
        features: ["Madera de calidad premium", "Acabado liso", "Resistente a la humedad"],
        specs: ["Espesor: 18mm", "Tamaño: 2.44x1.22m", "Grado: A/B"],
        availability: "En stock",
        faqs: [{ question: "¿Es resistente a la humedad?", answer: "Sí, tratado contra la humedad" }],
        connectivity: [],
      },
      {
        id: 18,
        name: "Contrachapado 12mm Estándar",
        category: "Madera Contrachapada",
        price: 55,
        image: "/plywood-standard.jpg",
        images: ["/plywood-standard.jpg"],
        brand: "WoodPro",
        description: "Lámina de contrachapado estándar",
        features: ["Madera estándar de calidad", "Acabado básico", "Económico"],
        specs: ["Espesor: 12mm", "Tamaño: 2.44x1.22m", "Grado: C/D"],
        availability: "En stock",
        faqs: [{ question: "¿Puedo pintarlo?", answer: "Sí, acepta pintura y barniz" }],
        connectivity: [],
      },
    ],
  },
}

// Helper function to get all products as a flat array
export function getAllProducts() {
  const allProducts: any[] = []
  Object.values(PRODUCTS_DATA).forEach((category) => {
    allProducts.push(...category.products)
  })
  return allProducts
}

// Helper function to get product by ID
export function getProductById(id: number) {
  const allProducts = getAllProducts()
  return allProducts.find((p) => p.id === id)
}

// Helper function to get products by category
export function getProductsByCategory(category: string) {
  return PRODUCTS_DATA[category as keyof typeof PRODUCTS_DATA]
}

// Helper function to get related products (same category, excluding current product)
export function getRelatedProducts(productId: number, limit = 3) {
  const product = getProductById(productId)
  if (!product) return []

  const categoryData = PRODUCTS_DATA[product.category.toLowerCase().replace(/\s+/g, "-") as keyof typeof PRODUCTS_DATA]
  if (!categoryData) return []

  return categoryData.products.filter((p) => p.id !== productId).slice(0, limit)
}
